set FLASK_APP=dokueiexp
set FLASK_ENV=development
set USERS_CSV=tests/users.csv
set CASE_IDS_TXT=tests/case_ids.txt
set ITEMS_CSV=tests/items.csv
set DIAGNOSIS_CSV=tests/diagnosis.csv
set REF_DATA_CSV=tests/reference.csv
set INTERVAL=1
set SESSION_LIFETIME=30
set RECORD_DB=sqlite:///tests/records.sqlite3
flask run
